spring:
  datasource:
    url: jdbc:h2:mem:starter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # h2를 이용할 때 hibernate를 통한 테이블 생성 후 data.sql 을 실행시키기 위함
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true