spring:
  config:
    import:
      - optional:config/env.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: sadfjkldsjafklbjvkclxjbvklsjrekwlsercret
  expiration-ms: 3600000
  refresh-expiration-ms: 86400000